### ISSUE TITLE
Tyk not allowing CORS OPTIONS from browser

### ISSUE THREAD

**Issue by jesucarr** [lonelycode/tyk#129]
I have an API endpoint called /ping that returns pong. When trying to run it behind Tyk I have it working if I run:

    curl -v -H "authorization: 5637c03e3d24390001000001bf5e71a3d8e246ca5f76403786c14c75" -H "Origin: http://localhost:3000" -H "Accept: */*" http://testoyk.docker:8888/payfer/ping
    * Hostname was NOT found in DNS cache
    *   Trying 192.168.99.100...
    * Connected to testorg.tyk.docker (192.168.99.100) port 8888 (#0)
    > GET /payfer/ping HTTP/1.1
    > User-Agent: curl/7.35.0
    > Host: testorg.tyk.docker:8888
    > authorization: 5637c03e3d24390001000001bf5e71a3d8e246ca5f76403786c14c75
    > Origin: http://localhost:3000
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Date: Tue, 03 Nov 2015 17:07:39 GMT
    < Content-Type: text/html; charset=utf-8
    < Content-Length: 5
    < Connection: keep-alive
    < Access-Control-Allow-Credentials: true
    < Access-Control-Allow-Origin: http://localhost:3000
    < Etag: W/"5-8KaHoy+18GpyU+JZEm/gWg"
    < Vary: Origin, Accept-Encoding
    < X-Powered-By: Express
    < X-Ratelimit-Limit: -1
    < X-Ratelimit-Remaining: 0
    < X-Ratelimit-Reset: 1446547351
    < 
    pong
    * Connection #0 to host testorg.tyk.docker left intact

However when trying to replicate the request from the browser with jQuery I get an CORS OPTIONS error. Here the logs:

<img width="638" alt="screen shot 2015-11-03 at 18 48 38" src="https://cloud.githubusercontent.com/assets/28097/10916396/9a6e0118-825b-11e5-937c-6dabfa4d9238.png">

The jQuery code is:

    $.ajax({
        url: "http://testorg.tyk.docker:8888/payfer/ping",
        headers: {"authorization": "5637c03e3d24390001000001bf5e71a3d8e246ca5f76403786c14c75"},
        success: function (res) {
            console.log(res);
        }
    });

The server is configured for CORS, so I have not enabled CORS in the Tyk API options. If I don't proxy through Tyk, it works.

At this point I'm not sure if I'm missing something or I'm hitting a bug. Any ideas? Thanks

**Comment by lonelycode** [comment]
I think it's the pre-flight request. It will be an OPTIONS request, and since it is generated by the browser, it will strip auth headers from the pre-flight.

When the options request hits Tyk, on a secured API path, it will still expect a header, and since that header is missing, block the pre-flight response, which in turn breaks the following (actual) request.

You've got two options:

1. Add OPTIONS and a wildcard to your endpoint designer, i.e. Method: `OPTIONS` Value: `{*}` select `"Ignored"` from the drop down (this will match anything one-level deep, e.g. `pong/`, `foo/` but not `foo/bar/baz`, thatwould need more wildcards, i.e.: `{*}/{*}/{*}`) What this will do is tell Tyk to not try and authenticate any of those requests and therefore let them through to your app.

2. Enable CORS in the Advanced options and set the relevant settings, then switch it off in your app. Then Tyk will handle pre-flight OPTIONS requests for you and write the relevant headers,

**Comment by jesucarr** [comment]
Thanks for the quick answer. Yes, both options worked. I opted for 2. since it's simpler and it means less hops and less requests to the api.

I guess this would be a very common use case and it would be worth to add to the docs.

**Comment by krsand** [comment]
Hi [jesucarr](https://github.com/jesucarr) , It would be really helpful if you describe Tyk CORS setting a bit  here.

Thanks!

**Comment by lonelycode** [comment]
@krsand I'd really suggest looking at our community forum, CORS is covered in excruciating detail.
