### ISSUE TITLE
Tyk Dashboard not finding keys created from Gateway API

### ISSUE THREAD

**Issue by jesucarr** [lonelycode/tyk#130]
I'm creating my own keys from my app using the Gateway API. This is the post request to /tyk/keys/{key}

    {
      "last_check":0,
      "allowance":1000,
      "rate":1000,
      "per":60,
      "expires":0,
      "quota_max":-1,
      "quota_renews":1446684367,
      "quota_remaining":-1,
      "quota_renewal_rate":60,
      "access_rights":{
        "c516a9b1c3e6498979e731d06cb8dc26":{
          "api_id":"c516a9b1c3e6498979e731d06cb8dc26",
          "api_name":"TestApi",
          "versions":["Default"]
        }
      },
      "apply_policy_id":"5637cf893d24390001000005",
      "tags":[],
      "meta_data":{},
      "basic_auth_data":{},
      "org_id": ""
    }

It is created fine, and it works using it for the requests. But when I put it in the Dashboard > Keys > Lookup Keys, it doesn't find it. Is that expected?

Also, it seems that the only way to find activity by key, is through the Developers > View Key Data, because the keys in Activity By Key are different from the real keys. So when I create the keys directly from the Gateway API, I have no way to see activity by key. Is there a way to do this?

Thanks

**Comment by lonelycode** [comment]
That's probably happening because the key does not belong to an organisation, and when the dashboard was set up it was set up with a primary organisation. 

The dashboard won't allow users of another organisations to pull tokens from a Tyk cluster if they key is not owned by the same organisation as that user.

To fix this, go to `Users -> Your User` in the dashboard

And copy the `RPC ID` value, then use this value in the `org_id` element of your token, and `PUT` it to the gateway REST API, you will get a modified response and it should now be searchable in the dashboard.

As for the way key analytics hare handled, the keys that you see in the key analytics are the hashed representation of the token, once a token is created, it is only available to the user once, right after creation. After that it is hashed and can never be retrieved and is never stored alongside analytics, this is why we attach this representation to a developer profile so that there is some form of identity management in place.

If you want don't care about keeping the keys secured in Tyk, you can disable key hashing by setting `hash_keys` to `false` in both your `tyk.conf` and `tyk_analytics.conf` files.

You will need to recreate your keys through.

**Comment by jesucarr** [comment]
I'm using the Docker install, and I don't have the RPC ID, only the Dashboard API key.

Is there any way to create the related Developer from the REST API? and is there any way to get the Developer from the Activity By Key?

**Comment by lonelycode** [comment]
You can get the Org ID by doing a request to your User object in the advanced API (https://tyk.io/advanced-api-v0-9/users/), so:

GET http://domain.com:3000/api/users/
With your users API key s the authorization header, you'll get a list of user objects, they will all have the same org ID

Alternatively, open up the browser console, select the network tab and then open the Users page (not developers), you'll see the same API request go out, if you examine the response preview, you'll see the Org ID.

Developer management can be done with the advanced API, the flow is the same as the portal, you create a developer, submit a v2 key request, and the approve it, the key will be generated and made public to the calling API once, and then hashed.

Developer API: https://tyk.io/advanced-api-v0-9/portal-developers/
Key Request API: https://tyk.io/advanced-api-v0-9/key-requests/

The advanced API goes via the dashboard, it is different from the raw node API as it restricts requests to specific orgs and users, but it has a ton of functionality.

**Comment by jesucarr** [comment]
I see. I completely missed the Advanced API. Now everything makes much more sense. Thanks!
