### ISSUE TITLE
Managing API definitions through REST

### ISSUE THREAD

**Issue by jimmidyson** [lonelycode/tyk#23]
Currently the `/apis/` endpoint lists APIs - how about POST/PUTting definitions there too? Thinking of using this in a Kubernetes/Docker environment & being able to update API definitions through REST calls rather than adding files or editing the database would be pretty useful. (Love the project by the way!)

**Comment by camann9** [comment]
I also like the idea of providing a complete endpoint for APIs. I think Tyk is awesome because it takes so much hassle out of API management and because it does exactly the stuff one would expect. But it has some inconsistencies in the API, one of which is the /apis endpoint.

**Comment by lonelycode** [comment]
We're still reviewing this feature request. 

The core issue with API management via the endpoint is that when tyk is deployed as multiple nodes across VM's (a pretty traditional deployment scenario tbh), writing an API Definition to file and reloading is inefficient as it introduces the risk of files going out of sync across the nodes. 

The dashboard has an API endpoint that will write to the DB to update a definition (in the licensed version, it will also trigger a hot-reload event and update the whole cluster). We're still writing all the documentation for the dashboard API, it's a lot bigger and stricter than the Tyk Gateway.

**Comment by camann9** [comment]
Ok, I understand. But now I can create APIs via the dashboard and I can create keys (tokens) via the Gateway. Both end up in the same Redis (if Redis is used). The architectural problem I see is that the Dashboard and the Gateway communicate via Redis and MongoDB and not via the Tyk API.

As long as communication is done in this way there is never a real incentive to add new functionality to the API since it is always possible to just communicate between dashboard and gateway via the database (as it happened with the /apis endpoint).

Maybe it would be an idea to have a master that manages (/owns) the configuration and defines the endpoints (plus purges statistics). Then the nodes would just need to have access to the Redis and the MongoDB dependency would be gone. The master would offer the REST interface and the Dashboard would communicate with the master via the REST interface. I drew a little ugly diagram to make my idea clearer: http://i.imgur.com/pu3nOaB.png

As I said before, I really like the idea of Tyk and its simplicity. But especially because of this I don't like the idea of making the Dashboard the master. It just doesn't sound right from a design point of view to add API components to the GUI.

**Comment by lonelycode** [comment]
There might be a bit of a misconception as to the architecture of Tyk, the dashboard speaks to Tyk via the REST API exclusively, it is essentially a client. it also serves as a CRUD GUI for putting definitions into the DB but that's about it, at it's core, it only ever speaks to Tyk directly, otherwise there would be two interfaces and that *would be* bad architecture :-).

On start, Tyk pulls it's configurations either from disk or from Mongo and they remain in memory, in this case, Mongo basically acts as the Master you mention in your diagram, currently it's basically a dirty object store. in multi-node configurations only one tyk node would be configured to purge.

A key issue here is fail-over and accidentally creating a SPOF, both Redis and MongoDB can be clustered well, so they offer a safe place to store keys and configurations. Creating a new service would seem dangerous, as if it goes down then your management infrastructure is gone.

This can be overcome though - but it means a rethink (and worth investigation).

If we embedded the API Definition management to live inside a Master, and assume that the master is actually just a Tyk node, then there is another possibility:

- Tyk nodes create a quorum, they reach a consensus to elect a master, this master's configurations are synchronised and flushed to disk across the cluster
- If the master fails, the quorum elects a new master
- Reloading the master should then reload the remaining cluster and re-synch configurations
- Adding new nodes means the quorum grows

The only problem to solve is:
- Notifying a registry where the master is (although this is trivial)
- Speed of synchronisation and reload (it needs to be extremely quick in HA envs), updates need to travel through the nodes, be flushed and then reloaded all at once.
- Figuring out how to make service discovery seamless

I quite like the idea, but I feel it needs some deep consideration. I'll put it in the roadmap, as it serves to make the application more resilient.

thanks! :-D

**Comment by lonelycode** [comment]
We will be adding the capability to post new definitions into a Tyk node, and it flushes them to disk. A hot reload call after this would make the definition live.

Any multi-process and multi-node installation will need to target all nodes in order for them to be in sync.

For master -> slave writes, it is recommended to use the advanced API that ships with the dashboard. This will also be fully documented.

**Comment by lonelycode** [comment]
Fixed in master branch.
