### ISSUE TITLE
analytics data purge

### ISSUE THREAD

**Issue by samek** [lonelycode/tyk#52]
Do we have to watch out for analytics data not filling up mongoldb or is it purged automatically ?

**Comment by lonelycode** [comment]
You can set a time limit to kill off analytics data, ever since 1.4:

"Added expiry TTL to tykcommon, data expiry headers will be added to all analytics records, set `expire_analytics_after` to `0` to have data live indefinetely (currently 100 years), set to anything above zero for data in MongoDB to be removed after `x` seconds. **requirement**: You must create an expiry TTL index on the tyk_analytics collection manually (http://docs.mongodb.org/manual/tutorial/expire-data/). If you do not wish mongo to manage data warehousing at all, simply do not create the index."

**Comment by samek** [comment]
tnx.
