### ISSUE TITLE
Endpoint Designer requires at least one option to be checked in order to save an endpoint

### ISSUE THREAD

**Issue by lyptt** [lonelycode/tyk#61]
I'm not entirely sure why, but when working with the endpoint designer in the Dashboard, at least one of Cache, Whitelist, Blacklist, Ignore, Transform, Headers, or Mock must be checked in order for the endpoint to be saved. 

If you don't check any of these options, the endpoint is lost when you hit the Update button.

**Comment by lonelycode** [comment]
HI, that makes sense - you only list endpoints in the designer if you want to have actions applied to it, otherwise the endpoint ill ot be marked as an exception.

By default Tyk will proxy everything, unless you set up an endpoint as one of the lists, in which case the API switches modes.

The only odd exception is mocks - a mocked endpoint MUST be attached to a list (usually ignore or white-list), because it piggybacks on the middleware that handles the path finding to apply the list rules.

**Comment by DavidTPate** [comment]
> The only odd exception is mocks - a mocked endpoint MUST be attached to a list (usually ignore or white-list), because it piggybacks on the middleware that handles the path finding to apply the list rules.

That makes sense now why I couldn't create a single mocked end-point. Would definitely be good to convey this as an error or something in the UI/API when someone tries to create a mock without it being attached to a list.

**Comment by lonelycode** [comment]
That's a good idea, there's some rules in place that enable / disable checkboxes to stop certain impossible configurations from being made, so adding a warning or a tool-tip to catch this would probably benefit users. Will mark as an enhancement.

**Comment by DavidTPate** [comment]
:+1: thanks @lonelycode

**Comment by lyptt** [comment]
Thanks for the feedback, that makes sense!

**Comment by lonelycode** [comment]
This is changed now in the altes verson - no more checkboxes. Warnings are now in place to ensure the correct options are selected.
