### ISSUE TITLE
Support for another datastore?

### ISSUE THREAD

**Issue by DavidTPate** [lonelycode/tyk#62]
Right now to run on a non-file system based configuration MongoDB is required. I'm wondering if there are any plans to look at adding support for another datastore. I ask because I would love to be able to use a managed service (such as AWS RDS) to manage my datastore for Tyk instead of having to do it myself.

I'm not sure of the reasons why MongoDB was chosen, but I'm assuming it was due to it being a document database. Maybe something like DynamoDB would be a good fit for it. Or if there just needs to be support for JSON fields then maybe MySQL is a better fit now with the addition of JSON support.

**Comment by lonelycode** [comment]
We get asked this a lot :-)

Mongo was chosen for the built in aggregation framework, it allows us
to offload analytics processing entirely to the database with no data
crunching code at all in our base and is quite efficient and very flexible
(we can upgrade analytics data without affecting backwards comlatability).

It's possible to add a different analytics storage engine to the gateway as
a new 'purger' - similar to the CSV one, e.g. If you had your own BI such
as Tableau.

However for the portal and dashboard the coupling is quite tight so major
changes would be needed to start using a new DB (not big fans of ORMs here).

We use http://compose.io for a managed service since there is no RDS
version of Mongo, it does quite well. There are some issues with hooking up
a replica set with the current configs though which we are working on (the
URL connection string provided by compose needs slight modification).

**Comment by schellkenig** [comment]
How did you configure compose with mongo ssl?
